[versions]
purpur = "1.19.4-R0.1-SNAPSHOT"

dazzleconf = "1.3.0-M2"
iridiumcolorapi = "1.2.0"

gson = "2.10.1"

[libraries]
purpur = { group = "org.purpurmc.purpur", name = "purpur-api", version.ref = "purpur" }

dazzleconf = { group = "space.arim.dazzleconf", name = "dazzleconf-ext-snakeyaml", version.ref = "dazzleconf" }
iridiumcolorapi = { group = "com.github.VelexNetwork", name = "iridium-color-api", version.ref = "iridiumcolorapi" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version = "0.5.3" }
blossom = { id = "net.kyori.blossom", version = "1.2.0" }
